{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependaproxy.postgresql.fullname" . }}
  labels:
    {{- include "dependaproxy.postgresql.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    {{- include "dependaproxy.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
